# Example 1 - Data Manipulation

## Introductions

Performing any in-depth analysis is challenging. So over the years our team has introduced different teaching styles to smoothen the learning curve. This series of notebooks will help guide your team through the fundamentals of data science and will show you a prime example of a winning analysis. We highly encourage everyone to read through the examples and complete the workshop.

This year, we are going with a Wikipedia-style tutorial series where our tutorials for the week will be split into two different onebooks; one for the example analysis, and another for the workshops. Throughout the example, hyperlinks will connect the two workshops and will allow you to jump from notebook to notebook. These hyperlinks serve just like the ones on Wikipedia, they help round your knowledge if you come accross an unfamiliar concept in the examples. We found that students learnt best by supporting new concepts explained in the workshops with an actual example in an analysis.

Nonetheless, go through the material in whatever order you like! Don't feel scared to complete the workshops then view the Examples. Remember to ask for help on Slack if we didn't do a good enough job at explaining!

Best wishes,<br>
The STEM Fellowship Data Science Team

## Step 1: Looking At Data

The first step in any analysis is to look for a good dataset. You generally want datasets that aren't missing values, contains many descriptive variables, and pertains to a topic that could a candidate for an analysis. Our team has viewed dozens of datasets and struggled to select the best one for this analysis so don't get discouraged! We didn't know what our analysis should be so we brainstormed topics, gathered more datasets, and rejected ideas. This proccess takes a while but once your team has a direction you'll do fine.

Our team has decided to look at the Air Quality dataset provided by the EPA (United States Environmental Protection Agency). When finding data make sure to look for a README for context on the column headers.

 - The Dataset: https://aqs.epa.gov/aqsweb/airdata/download_files.html#main-content
 - README: https://aqs.epa.gov/aqsweb/airdata/FileFormats.html

Since the dataset contains 11 million rows we've provided a minimized version for those with less powerful computers. For benchmarks, it could run on a 7-year-old computer with 8GB of ram.

In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv("../datasets/annual_aqi_by_cbsa_2018.csv")
data2 = pd.read_csv("../datasets/annual_aqi_by_county_2018.csv")
data3 = pd.read_csv("../datasets/annual_conc_by_monitor_2018.csv")

In [3]:
data1.head()

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,"Aberdeen, WA",10140,2018,31,30,1,0,0,0,0,57,38,26,0,0,0,0,31,0
1,"Akron, OH",10420,2018,90,71,19,0,0,0,0,79,60,37,0,0,27,0,63,0
2,"Albany, GA",10500,2018,59,44,15,0,0,0,0,79,64,29,0,0,0,0,59,0
3,"Albany-Schenectady-Troy, NY",10580,2018,90,69,21,0,0,0,0,78,60,40,0,0,52,0,38,0
4,"Alexandria, LA",10780,2018,28,26,2,0,0,0,0,54,49,27,0,0,0,0,28,0

In [4]:
data2.head()

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,DeKalb,2018,58,58,0,0,0,0,0,44,37,31,0,0,58,0,0,0
1,Alabama,Etowah,2018,59,27,31,0,1,0,0,153,62,52,0,0,0,0,59,0
2,Alabama,Jefferson,2018,59,38,21,0,0,0,0,72,57,47,0,1,6,7,44,1
3,Alabama,Mobile,2018,59,55,4,0,0,0,0,53,38,17,0,0,0,20,39,0
4,Alabama,Morgan,2018,59,54,5,0,0,0,0,56,50,29,0,0,0,0,59,0

In [5]:
data3.head()

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
0,1,55,10,88502,3,33.991494,-85.992647,NAD83,Acceptable PM2.5 AQI & Speciation Mass,1 HOUR,...,16.1,12.0,6.3,GADSDEN C. COLLEGE,"1001 WALLACE DRIVE, GADSDEN, AL 35902",Alabama,Etowah,Gadsden,"Gadsden, AL",2018-05-09
1,1,55,10,88502,3,33.991494,-85.992647,NAD83,Acceptable PM2.5 AQI & Speciation Mass,24-HR BLK AVG,...,15.5,12.7,7.3,GADSDEN C. COLLEGE,"1001 WALLACE DRIVE, GADSDEN, AL 35902",Alabama,Etowah,Gadsden,"Gadsden, AL",2018-05-09
2,1,73,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,1 HOUR,...,2.8,1.7,0.2,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12
3,1,73,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,1 HOUR,...,0.7,0.3,0.0,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12
4,1,73,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,24-HR BLK AVG,...,0.9,0.5,0.1,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12

In [6]:
print(data1.columns)
print(data2.columns)
print(data3.columns)
#I googled around and found what a cbsa is https://en.wikipedia.org/wiki/Core-based_statistical_area

Index(['CBSA', 'CBSA Code', 'Year', 'Days with AQI', 'Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'],
      dtype='object')
Index(['State', 'County', 'Year', 'Days with AQI', 'Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'],
      dtype='object')
Index(['State Code', 'County Code', 'Site Num', 'Parameter Code', 'POC',
       'Latitude', 'Longitude', 'Datum', 'Parameter Name', 'Sample Duration',
       'Pollutant Standard', 'Metric Used', 'Method Name', 'Year',
       'Units of Measure', 'Event Type', 'Observation Count',
       'Observation Percent', 'Completeness Indicator', 'Valid Day Count',
       'Required Day Count', 'Exceptional Data Count', 'Null Data Count',
       'Primary Exceedance Count', 'Secondary Exceedance Count',
       'Certification Indicator', 'Num Obs Below MDL', 'Arithmetic Mean',
       'Arithmetic Standard Dev', '1st Max Value', '1st Max DateTime',
       '2nd Max Value', '2nd Max DateTime', '3rd Max Value',
       '3rd Max DateTime', '4th Max Value', '4th Max DateTime',
       '1st Max Non Overlapping Value', '1st NO Max DateTime',
       '2nd Max Non Overlapping Value', '2nd NO Max DateTime',
       '99th Percentile', '98th Percentile', '95th Percentile',
       '90th Percentile', '75th Percentile', '50th Percentile',
       '10th Percentile', 'Local Site Name', 'Address', 'State Name',
       'County Name', 'City Name', 'CBSA Name', 'Date of Last Change'],
      dtype='object')

In [7]:
# I only want the lat lon and Datum
data3_temp = data3[["Latitude","Longitude","Datum"]]
data3_temp.head(2)

    Latitude  Longitude  Datum
0  33.991494 -85.992647  NAD83
1  33.991494 -85.992647  NAD83

In [8]:
# I want to that one piece of data
data3_temp["Latitude"][3]

33.553055999999998

### Attribute selection
There are two paradigm for attribute selection,
iloc for Index based selection, loc for label based selection

In [9]:
# Index based selection
data3.iloc[1]

State Code                                                            1
County Code                                                          55
Site Num                                                             10
Parameter Code                                                    88502
POC                                                                   3
Latitude                                                        33.9915
Longitude                                                      -85.9926
Datum                                                             NAD83
Parameter Name                   Acceptable PM2.5 AQI & Speciation Mass
Sample Duration                                           24-HR BLK AVG
Pollutant Standard                                                  NaN
Metric Used                                             Observed Values
Method Name                                                         NaN
Year                                                               2018
Units of Measure                            Micrograms/cubic meter (LC)
Event Type                                                    No Events
Observation Count                                                    59
Observation Percent                                                  16
Completeness Indicator                                                N
Valid Day Count                                                      59
Required Day Count                                                  365
Exceptional Data Count                                                0
Null Data Count                                                       0
Primary Exceedance Count                                            NaN
Secondary Exceedance Count                                          NaN
Certification Indicator                      Certification not required
Num Obs Below MDL                                                     0
Arithmetic Mean                                                 13.2831
Arithmetic Standard Dev                                         7.21048
1st Max Value                                                      59.8
1st Max DateTime                                       2018-01-27 00:00
2nd Max Value                                                      20.6
2nd Max DateTime                                       2018-01-26 00:00
3rd Max Value                                                      20.1
3rd Max DateTime                                       2018-01-09 00:00
4th Max Value                                                      17.7
4th Max DateTime                                       2018-01-07 00:00
1st Max Non Overlapping Value                                       NaN
1st NO Max DateTime                                                 NaN
2nd Max Non Overlapping Value                                       NaN
2nd NO Max DateTime                                                 NaN
99th Percentile                                                    59.8
98th Percentile                                                    20.6
95th Percentile                                                    20.1
90th Percentile                                                    17.4
75th Percentile                                                    15.5
50th Percentile                                                    12.7
10th Percentile                                                     7.3
Local Site Name                                      GADSDEN C. COLLEGE
Address                           1001 WALLACE DRIVE, GADSDEN, AL 35902
State Name                                                      Alabama
County Name                                                      Etowah
City Name                                                       Gadsden
CBSA Name                                                   Gadsden, AL
Date of Last Change                                          2018-05-09
Name: 1, dtype: object

Both loc ,iloc are row-first, column-second. 
This means that it's marginally easier to retrieve rows, 
and marginally harder to get retrieve columns. 
To get a column with iloc, we can do the following:

In [10]:
data3_temp.iloc[:, 0].head(2)
# the operator : come from  native python, it means everything

0    33.991494
1    33.991494
Name: Latitude, dtype: float64

We can also combine this operator, to select data in a range
For example we want to select first, second and third entries

In [11]:
data3_temp.iloc[:3, 0]

0    33.991494
1    33.991494
2    33.553056
Name: Latitude, dtype: float64

You can also pass in a list

In [12]:
data3_temp.iloc[[1,2,3],0]

1    33.991494
2    33.553056
3    33.553056
Name: Latitude, dtype: float64

You can also make selection with negative number,
It will count from the end
For example if you want last 3 elements

In [13]:
data3_temp.iloc[-5:]

        Latitude   Longitude  Datum
14812  32.633671 -115.504995  WGS84
14813  32.466389 -114.768611  WGS84
14814  32.466389 -114.768611  WGS84
14815  32.466389 -114.768611  WGS84
14816  32.466389 -114.768611  WGS84

### Label based selection (loc)
It is similar to Index based selection
For example if i want first entry on country

In [17]:
data3.loc[0, 'Year']

2018

### Manipulating the index
We can manipulate the index in entry as we want it
Here is what happen if i set 'Country Code' As the index

In [21]:
data3.set_index("County Code").head()

,State Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,Pollutant Standard,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
County Code,,,,,,,,,,,,,,,,,,,,,
55,1,10,88502,3,33.991494,-85.992647,NAD83,Acceptable PM2.5 AQI & Speciation Mass,1 HOUR,NaN,...,16.1,12.0,6.3,GADSDEN C. COLLEGE,"1001 WALLACE DRIVE, GADSDEN, AL 35902",Alabama,Etowah,Gadsden,"Gadsden, AL",2018-05-09
55,1,10,88502,3,33.991494,-85.992647,NAD83,Acceptable PM2.5 AQI & Speciation Mass,24-HR BLK AVG,NaN,...,15.5,12.7,7.3,GADSDEN C. COLLEGE,"1001 WALLACE DRIVE, GADSDEN, AL 35902",Alabama,Etowah,Gadsden,"Gadsden, AL",2018-05-09
73,1,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,1 HOUR,SO2 1-hour 2010,...,2.8,1.7,0.2,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12
73,1,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,1 HOUR,SO2 Annual 1971,...,0.7,0.3,0.0,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12
73,1,23,42401,2,33.553056,-86.815000,WGS84,Sulfur dioxide,24-HR BLK AVG,SO2 24-hour 1971,...,0.9,0.5,0.1,North Birmingham,"NO. B'HAM,SOU R.R., 3009 28TH ST. NO.",Alabama,Jefferson,Birmingham,"Birmingham-Hoover, AL",2018-04-12

Performing a set_index when you can come up with an index for the dataset which is better than the current one.

### Conditional Selection
Sometimes we want to select data based on some conditions
Check what happen if i do this

In [27]:
data2.State == "Alabama"

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
Name: State, Length: 593, dtype: bool

This operation produced a Series of True/False booleans based on the county of each record.
This result can then be used inside of loc to select the relevant data:

In [28]:
data3.loc[data3== 'Alabama']

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,DeKalb,2018,58,58,0,0,0,0,0,44,37,31,0,0,58,0,0,0
1,Alabama,Etowah,2018,59,27,31,0,1,0,0,153,62,52,0,0,0,0,59,0
2,Alabama,Jefferson,2018,59,38,21,0,0,0,0,72,57,47,0,1,6,7,44,1
3,Alabama,Mobile,2018,59,55,4,0,0,0,0,53,38,17,0,0,0,20,39,0
4,Alabama,Morgan,2018,59,54,5,0,0,0,0,56,50,29,0,0,0,0,59,0
5,Alabama,Russell,2018,59,35,24,0,0,0,0,84,63,45,0,0,0,0,59,0
6,Alabama,Shelby,2018,58,57,0,1,0,0,0,124,9,0,0,0,0,58,0,0
7,Alabama,Sumter,2018,59,59,0,0,0,0,0,45,36,19,0,0,0,9,50,0
8,Alabama,Tuscaloosa,2018,54,43,11,0,0,0,0,62,54,38,0,0,0,0,54,0

Seems like first 9 entries are from Alabama!

We can use the ampersand (&) to bring the two conditions together:

In [35]:
data2.loc[(data2.State == 'Alabama') & (data2['Good Days']>40)]

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,DeKalb,2018,58,58,0,0,0,0,0,44,37,31,0,0,58,0,0,0
3,Alabama,Mobile,2018,59,55,4,0,0,0,0,53,38,17,0,0,0,20,39,0
4,Alabama,Morgan,2018,59,54,5,0,0,0,0,56,50,29,0,0,0,0,59,0
6,Alabama,Shelby,2018,58,57,0,1,0,0,0,124,9,0,0,0,0,58,0,0
7,Alabama,Sumter,2018,59,59,0,0,0,0,0,45,36,19,0,0,0,9,50,0
8,Alabama,Tuscaloosa,2018,54,43,11,0,0,0,0,62,54,38,0,0,0,0,54,0

And suppose want to know the data from Alabama or Good Days > 40, we can use a pipe ( | )

In [31]:
data2.loc[(data2.State == 'Alabama') | (data2['Good Days']>40)]

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,DeKalb,2018,58,58,0,0,0,0,0,44,37,31,0,0,58,0,0,0
1,Alabama,Etowah,2018,59,27,31,0,1,0,0,153,62,52,0,0,0,0,59,0
2,Alabama,Jefferson,2018,59,38,21,0,0,0,0,72,57,47,0,1,6,7,44,1
3,Alabama,Mobile,2018,59,55,4,0,0,0,0,53,38,17,0,0,0,20,39,0
4,Alabama,Morgan,2018,59,54,5,0,0,0,0,56,50,29,0,0,0,0,59,0
5,Alabama,Russell,2018,59,35,24,0,0,0,0,84,63,45,0,0,0,0,59,0
6,Alabama,Shelby,2018,58,57,0,1,0,0,0,124,9,0,0,0,0,58,0,0
7,Alabama,Sumter,2018,59,59,0,0,0,0,0,45,36,19,0,0,0,9,50,0
8,Alabama,Tuscaloosa,2018,54,43,11,0,0,0,0,62,54,38,0,0,0,0,54,0
9,Alaska,Denali,2018,90,90,0,0,0,0,0,49,44,39,0,0,90,0,0,0
10,Arizona,Apache,2018,94,94,0,0,0,0,0,26,16,10,0,0,0,0,8,86
11,Arizona,Cochise,2018,90,85,5,0,0,0,0,63,49,44,0,0,78,0,1,11
12,Arizona,Coconino,2018,90,89,1,0,0,0,0,61,47,43,0,0,90,0,0,0
14,Arizona,La Paz,2018,90,87,3,0,0,0,0,67,48,41,0,0,87,0,3,0
16,Arizona,Mohave,2018,90,88,2,0,0,0,0,82,21,9,0,0,0,0,0,90
17,Arizona,Navajo,2018,90,89,1,0,0,0,0,54,47,40,0,0,86,0,0,4
18,Arizona,Pima,2018,90,71,19,0,0,0,0,85,56,39,0,0,0,0,0,90
19,Arizona,Pinal,2018,90,83,7,0,0,0,0,67,50,44,0,0,90,0,0,0
20,Arizona,Santa Cruz,2018,89,61,27,0,1,0,0,183,64,39,0,0,0,0,50,39
21,Arizona,Yavapai,2018,90,90,0,0,0,0,0,50,46,39,0,0,90,0,0,0
22,Arizona,Yuma,2018,90,72,16,2,0,0,0,130,59,44,0,0,54,0,6,30
25,Arkansas,Clark,2018,59,59,0,0,0,0,0,40,36,28,0,0,59,0,0,0
26,Arkansas,Crittenden,2018,90,85,5,0,0,0,0,67,47,36,0,6,50,0,34,0
29,Arkansas,Newton,2018,90,88,2,0,0,0,0,84,45,34,0,0,90,0,0,0
30,Arkansas,Polk,2018,90,82,8,0,0,0,0,93,50,38,0,0,78,0,12,0
31,Arkansas,Pulaski,2018,90,78,12,0,0,0,0,74,52,39,0,0,38,0,52,0
32,Arkansas,Union,2018,90,79,11,0,0,0,0,66,54,34,0,0,0,0,90,0
33,Arkansas,Washington,2018,90,72,18,0,0,0,0,87,59,38,0,0,57,0,33,0
35,California,Colusa,2018,81,81,0,0,0,0,0,41,19,7,0,0,0,0,81,0
37,California,Fresno,2018,120,88,29,3,0,0,0,128,74,43,0,0,90,0,30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Utah,San Juan,2018,90,89,1,0,0,0,0,58,46,41,0,0,90,0,0,0
492,Utah,Tooele,2018,120,102,17,1,0,0,0,121,58,42,0,0,102,0,18,0
493,Utah,Uintah,2018,120,97,23,0,0,0,0,84,58,44,0,0,113,0,7,0
494,Utah,Utah,2018,120,108,12,0,0,0,0,74,51,36,0,10,58,0,48,4
495,Utah,Washington,2018,90,90,0,0,0,0,0,47,44,33,0,1,86,0,3,0
496,Utah,Weber,2018,120,98,22,0,0,0,0,97,54,43,0,32,71,0,13,4
499,Virginia,Botetourt,2018,90,90,0,0,0,0,0,41,19,1,0,0,0,90,0,0
504,Virginia,Covington City,2018,90,90,0,0,0,0,0,43,16,3,0,0,0,90,0,0
505,Virginia,Fairfax,2018,66,61,5,0,0,0,0,66,45,25,0,0,0,0,58,8
507,Virginia,Giles,2018,85,77,6,2,0,0,0,118,49,33,0,0,43,42,0,0
513,Virginia,Madison,2018,89,89,0,0,0,0,0,48,44,38,0,0,89,0,0,0
515,Virginia,Prince Edward,2018,58,58,0,0,0,0,0,42,37,32,0,0,58,0,0,0
551,West Virginia,Brooke,2018,90,88,2,0,0,0,0,62,24,11,0,0,0,56,0,34
553,West Virginia,Gilmer,2018,59,59,0,0,0,0,0,44,36,30,0,0,59,0,0,0
555,West Virginia,Hancock,2018,90,90,0,0,0,0,0,48,41,13,0,0,31,32,0,27
556,West Virginia,Kanawha,2018,90,77,13,0,0,0,0,67,52,42,0,0,28,0,62,0
557,West Virginia,Marshall,2018,90,56,34,0,0,0,0,93,68,44,0,0,0,0,90,0
558,West Virginia,Mason,2018,113,112,1,0,0,0,0,60,10,1,0,0,0,113,0,0
559,West Virginia,Mineral,2018,89,64,9,9,7,0,0,200,141,4,0,0,0,89,0,0
560,West Virginia,Monongalia,2018,57,57,0,0,0,0,0,44,40,29,0,0,30,27,0,0
562,West Virginia,Tucker,2018,59,59,0,0,0,0,0,44,38,32,0,0,59,0,0,0
563,West Virginia,Wood,2018,88,87,1,0,0,0,0,57,37,11,0,0,31,57,0,0
578,Wisconsin,Taylor,2018,59,56,3,0,0,0,0,55,47,34,0,0,50,0,9,0
581,Wyoming,Albany,2018,68,67,1,0,0,0,0,54,48,44,0,0,59,0,6,3
582,Wyoming,Campbell,2018,90,89,1,0,0,0,0,76,20,12,0,0,0,0,0,90
583,Wyoming,Converse,2018,90,90,0,0,0,0,0,47,44,38,0,0,89,0,0,1
586,Wyoming,Lincoln,2018,90,89,1,0,0,0,0,55,25,6,0,0,0,0,0,90
590,Wyoming,Sublette,2018,90,89,1,0,0,0,0,58,46,43,0,0,90,0,0,0
591,Wyoming,Sweetwater,2018,90,89,1,0,0,0,0,65,45,40,0,0,89,0,1,0
592,Wyoming,Teton,2018,90,86,4,0,0,0,0,58,49,41,0,0,87,0,3,0

pandas comes with a few pre-built conditional selectors, We will highlight the most useful two. The first one in isin.

The first is isin. isin is lets you select data whose value "is in" a list of values.

For example, here's how we can use it to select data from Arizona and California

In [34]:
data2.loc[data2.State.isin(['Arizona', 'California'])]

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
10,Arizona,Apache,2018,94,94,0,0,0,0,0,26,16,10,0,0,0,0,8,86
11,Arizona,Cochise,2018,90,85,5,0,0,0,0,63,49,44,0,0,78,0,1,11
12,Arizona,Coconino,2018,90,89,1,0,0,0,0,61,47,43,0,0,90,0,0,0
13,Arizona,Gila,2018,90,34,33,20,3,0,0,181,126,64,0,0,29,57,0,4
14,Arizona,La Paz,2018,90,87,3,0,0,0,0,67,48,41,0,0,87,0,3,0
15,Arizona,Maricopa,2018,90,17,71,1,0,1,0,249,80,62,0,6,21,0,26,37
16,Arizona,Mohave,2018,90,88,2,0,0,0,0,82,21,9,0,0,0,0,0,90
17,Arizona,Navajo,2018,90,89,1,0,0,0,0,54,47,40,0,0,86,0,0,4
18,Arizona,Pima,2018,90,71,19,0,0,0,0,85,56,39,0,0,0,0,0,90
19,Arizona,Pinal,2018,90,83,7,0,0,0,0,67,50,44,0,0,90,0,0,0
20,Arizona,Santa Cruz,2018,89,61,27,0,1,0,0,183,64,39,0,0,0,0,50,39
21,Arizona,Yavapai,2018,90,90,0,0,0,0,0,50,46,39,0,0,90,0,0,0
22,Arizona,Yuma,2018,90,72,16,2,0,0,0,130,59,44,0,0,54,0,6,30
34,California,Alameda,2018,59,26,32,1,0,0,0,110,83,52,0,4,4,0,51,0
35,California,Colusa,2018,81,81,0,0,0,0,0,41,19,7,0,0,0,0,81,0
36,California,Contra Costa,2018,59,37,20,2,0,0,0,145,81,48,0,0,4,0,55,0
37,California,Fresno,2018,120,88,29,3,0,0,0,128,74,43,0,0,90,0,30,0
38,California,Humboldt,2018,88,86,2,0,0,0,0,53,38,29,0,3,64,0,15,6
39,California,Inyo,2018,88,86,2,0,0,0,0,71,46,40,0,0,84,0,0,4
40,California,Kern,2018,120,106,14,0,0,0,0,80,52,32,0,0,47,0,70,3
41,California,Kings,2018,89,74,15,0,0,0,0,98,57,38,0,0,60,0,0,29
42,California,Marin,2018,59,47,11,1,0,0,0,123,66,36,0,6,16,0,37,0
43,California,Mariposa,2018,90,90,0,0,0,0,0,49,45,40,0,0,90,0,0,0
44,California,Mono,2018,90,89,1,0,0,0,0,54,35,15,0,0,0,0,0,90
45,California,Monterey,2018,59,56,3,0,0,0,0,64,40,34,0,1,51,0,6,1
46,California,Napa,2018,59,22,37,0,0,0,0,89,72,54,0,0,2,0,57,0
47,California,Nevada,2018,31,29,2,0,0,0,0,67,49,44,0,0,31,0,0,0
48,California,Placer,2018,90,89,1,0,0,0,0,52,47,40,0,0,84,0,6,0
49,California,Riverside,2018,120,71,34,11,2,2,0,241,112,46,0,0,91,0,5,24
50,California,San Benito,2018,90,88,2,0,0,0,0,59,43,37,0,0,83,0,7,0
51,California,San Bernardino,2018,90,84,6,0,0,0,0,80,49,44,0,0,90,0,0,0
52,California,San Diego,2018,17,17,0,0,0,0,0,38,29,11,0,0,0,0,0,17
53,California,San Francisco,2018,59,35,23,1,0,0,0,111,72,45,0,8,10,0,41,0
54,California,San Mateo,2018,59,43,16,0,0,0,0,83,69,36,0,9,17,0,33,0
55,California,Santa Clara,2018,59,38,19,2,0,0,0,124,70,40,0,7,12,0,40,0
56,California,Santa Cruz,2018,59,58,1,0,0,0,0,55,40,34,0,0,36,0,23,0
57,California,Shasta,2018,86,86,0,0,0,0,0,49,44,40,0,0,86,0,0,0
58,California,Solano,2018,89,68,20,1,0,0,0,132,63,39,0,1,46,0,42,0
59,California,Sonoma,2018,59,50,9,0,0,0,0,84,59,35,0,0,27,0,32,0
60,California,Tulare,2018,90,82,8,0,0,0,0,74,50,37,0,0,90,0,0,0
61,California,Ventura,2018,90,72,18,0,0,0,0,94,63,44,0,1,52,0,35,2
62,California,Yolo,2018,90,90,0,0,0,0,0,48,40,34,0,0,90,0,0,0

The second is isnull (and its companion notnull). These methods let you highlight values which are or are not empty (NaN). For example, to filter out data lacking a City Name in the dataset, here's what we would do:

In [39]:
data3.loc[data3['City Name'].isnull()]

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,75th Percentile,50th Percentile,10th Percentile,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
59,1,73,1005,68102,1,33.331111,-87.003611,WGS84,Sample Volume,24 HOUR,...,24.000,24.000,24.000,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
60,1,73,1005,68102,2,33.331111,-87.003611,WGS84,Sample Volume,24 HOUR,...,24.000,24.000,24.000,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
61,1,73,1005,68105,1,33.331111,-87.003611,WGS84,Average Ambient Temperature,24 HOUR,...,16.800,10.900,-1.400,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
62,1,73,1005,68105,2,33.331111,-87.003611,WGS84,Average Ambient Temperature,24 HOUR,...,14.000,12.800,-1.000,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
63,1,73,1005,68108,1,33.331111,-87.003611,WGS84,Average Ambient Pressure,24 HOUR,...,757.000,751.000,745.000,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
64,1,73,1005,68108,2,33.331111,-87.003611,WGS84,Average Ambient Pressure,24 HOUR,...,758.000,751.000,748.000,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
65,1,73,1005,88101,1,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,9.000,7.400,5.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
66,1,73,1005,88101,1,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,9.000,7.400,5.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
67,1,73,1005,88101,1,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,9.000,7.400,5.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
68,1,73,1005,88101,1,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,9.000,7.400,5.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
69,1,73,1005,88101,2,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,8.500,7.000,4.800,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
70,1,73,1005,88101,2,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,8.500,7.000,4.800,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
71,1,73,1005,88101,2,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,8.500,7.000,4.800,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
72,1,73,1005,88101,2,33.331111,-87.003611,WGS84,PM2.5 - Local Conditions,24 HOUR,...,8.500,7.000,4.800,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
73,1,73,1005,88502,3,33.331111,-87.003611,WGS84,Acceptable PM2.5 AQI & Speciation Mass,1 HOUR,...,9.600,7.300,3.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
74,1,73,1005,88502,3,33.331111,-87.003611,WGS84,Acceptable PM2.5 AQI & Speciation Mass,24-HR BLK AVG,...,9.400,7.700,4.600,McAdory,ROUTE 8 MCADORY,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
132,1,73,5003,88502,3,33.801667,-86.942500,WGS84,Acceptable PM2.5 AQI & Speciation Mass,1 HOUR,...,9.100,6.800,2.400,Corner,10005 CORNER SCHOOL ROAD,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
133,1,73,5003,88502,3,33.801667,-86.942500,WGS84,Acceptable PM2.5 AQI & Speciation Mass,24-HR BLK AVG,...,8.700,6.900,4.000,Corner,10005 CORNER SCHOOL ROAD,Alabama,Jefferson,NaN,"Birmingham-Hoover, AL",2018-04-12
159,1,119,3,42401,1,32.362606,-88.277992,NAD83,Sulfur dioxide,1 HOUR,...,0.900,0.400,-0.400,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
160,1,119,3,42401,1,32.362606,-88.277992,NAD83,Sulfur dioxide,1 HOUR,...,0.100,0.000,-0.600,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
161,1,119,3,42401,1,32.362606,-88.277992,NAD83,Sulfur dioxide,24-HR BLK AVG,...,0.200,0.000,-0.600,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
162,1,119,3,42401,1,32.362606,-88.277992,NAD83,Sulfur dioxide,3-HR BLK AVG,...,0.100,0.000,-0.600,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
163,1,119,3,42406,1,32.362606,-88.277992,NAD83,SO2 max 5-min avg,1 HOUR,...,0.100,0.000,-0.600,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
164,1,119,3,88502,3,32.362606,-88.277992,NAD83,Acceptable PM2.5 AQI & Speciation Mass,1 HOUR,...,8.200,5.400,0.300,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
165,1,119,3,88502,3,32.362606,-88.277992,NAD83,Acceptable PM2.5 AQI & Speciation Mass,24-HR BLK AVG,...,7.600,5.200,1.800,"Ward, Sumter Co.","NNE of Ward Post Office, Sumter Co., Alabama",Alabama,Sumter,NaN,NaN,2018-05-09
168,2,68,3,61101,1,63.723200,-148.967600,WGS84,Wind Speed - Scalar,1 HOUR,...,2.900,1.700,0.800,NaN,DENALI NATIONAL PARK,Alaska,Denali,NaN,NaN,2018-05-17
169,2,68,3,61103,1,63.723200,-148.967600,WGS84,Wind Speed - Resultant,1 HOUR,...,2.300,1.000,0.400,NaN,DENALI NATIONAL PARK,Alaska,Denali,NaN,NaN,2018-05-17
170,2,68,3,61104,1,63.723200,-148.967600,WGS84,Wind Direction - Resultant,1 HOUR,...,294.000,185.000,20.000,NaN,DENALI NATIONAL PARK,Alaska,Denali,NaN,NaN,2018-05-17
171,2,68,3,61106,1,63.723200,-148.967600,WGS84,Std Dev Hz Wind Direction,1 HOUR,...,59.000,48.000,22.000,NaN,DENALI NATIONAL PARK,Alaska,Denali,NaN,NaN,2018-05-17
172,2,68,3,62101,1,63.723200,-148.967600,WGS84,Outdoor Temperature,1 HOUR,...,24.000,15.000,-13.000,NaN,DENALI NATIONAL PARK,Alaska,Denali,NaN,NaN,2018-05-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14746,56,39,8,65102,1,43.670833,-110.599472,WGS84,Rain/melt precipitation,1 HOUR,...,0.000,0.000,0.000,Grand Teton NP - Science School,Grand Teton NP - Science School,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14765,56,39,1011,44201,1,44.565360,-110.400340,WGS84,Ozone,1 HOUR,...,0.049,0.046,0.041,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14766,56,39,1011,44201,1,44.565360,-110.400340,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.048,0.044,0.039,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14767,56,39,1011,44201,1,44.565360,-110.400340,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.048,0.044,0.039,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14768,56,39,1011,44201,1,44.565360,-110.400340,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.048,0.044,0.039,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14769,56,39,1011,61101,1,44.565360,-110.400340,WGS84,Wind Speed - Scalar,1 HOUR,...,4.100,2.500,1.200,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14770,56,39,1011,61103,1,44.565360,-110.400340,WGS84,Wind Speed - Resultant,1 HOUR,...,3.300,1.900,0.600,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14771,56,39,1011,61104,1,44.565360,-110.400340,WGS84,Wind Direction - Resultant,1 HOUR,...,255.000,220.000,146.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14772,56,39,1011,61106,1,44.565360,-110.400340,WGS84,Std Dev Hz Wind Direction,1 HOUR,...,47.000,39.000,27.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14773,56,39,1011,62101,1,44.565360,-110.400340,WGS84,Outdoor Temperature,1 HOUR,...,26.000,20.000,5.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14774,56,39,1011,62201,1,44.565360,-110.400340,WGS84,Relative Humidity,1 HOUR,...,86.000,82.000,60.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14775,56,39,1011,63301,1,44.565360,-110.400340,WGS84,Solar radiation,1 HOUR,...,0.040,0.000,0.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14776,56,39,1011,65102,1,44.565360,-110.400340,WGS84,Rain/melt precipitation,1 HOUR,...,0.000,0.000,0.000,"Yellowstone National Park, Water Tank",YELLOWSTONE NATIONAL PARK,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14777,56,39,1013,42101,1,44.373056,-110.830833,WGS84,Carbon monoxide,1 HOUR,...,0.180,0.167,0.144,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14778,56,39,1013,42101,1,44.373056,-110.830833,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,...,0.200,0.200,0.100,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14779,56,39,1013,61101,1,44.373056,-110.830833,WGS84,Wind Speed - Scalar,1 HOUR,...,4.900,2.900,1.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14780,56,39,1013,61103,1,44.373056,-110.830833,WGS84,Wind Speed - Resultant,1 HOUR,...,4.300,2.300,0.600,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14781,56,39,1013,61104,1,44.373056,-110.830833,WGS84,Wind Direction - Resultant,1 HOUR,...,235.000,206.000,113.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14782,56,39,1013,61106,1,44.373056,-110.830833,WGS84,Std Dev Hz Wind Direction,1 HOUR,...,45.000,31.000,21.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14783,56,39,1013,62101,1,44.373056,-110.830833,WGS84,Outdoor Temperature,1 HOUR,...,28.000,22.000,3.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14784,56,39,1013,62201,1,44.373056,-110.830833,WGS84,Relative Humidity,1 HOUR,...,87.000,81.000,59.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14785,56,39,1013,88101,1,44.373056,-110.830833,WGS84,PM2.5 - Local Conditions,1 HOUR,...,3.000,1.000,-1.000,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14786,56,39,1013,88101,1,44.373056,-110.830833,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,...,1.800,1.300,0.400,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14787,56,39,1013,88101,1,44.373056,-110.830833,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,...,1.800,1.300,0.400,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14788,56,39,1013,88101,1,44.373056,-110.830833,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,...,1.800,1.300,0.400,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14789,56,39,1013,88101,1,44.373056,-110.830833,WGS84,PM2.5 - Local Conditions,24-HR BLK AVG,...,1.800,1.300,0.400,Yellowstone National Park - Old Faithful Snow ...,Yellowstone National Park - Old Faithful Snow ...,Wyoming,Teton,NaN,"Jackson, WY-ID",2018-05-17
14813,80,26,8012,44201,1,32.466389,-114.768611,WGS84,Ozone,1 HOUR,...,0.045,0.042,0.036,San Luis Rio Colorado Well 10,Calle 15 & Venustiano Carranza Water Well #10,Country Of Mexico,SONORA,NaN,NaN,2018-04-12
14814,80,26,8012,44201,1,32.466389,-114.768611,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.041,0.037,0.029,San Luis Rio Colorado Well 10,Calle 15 & Venustiano Carranza Water Well #10,Country Of Mexico,SONORA,NaN,NaN,2018-04-12
14815,80,26,8012,44201,1,32.466389,-114.768611,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.041,0.037,0.029,San Luis Rio Colorado Well 10,Calle 15 & Venustiano Carranza Water Well #10,Country Of Mexico,SONORA,NaN,NaN,2018-04-12
14816,80,26,8012,44201,1,32.466389,-114.768611,WGS84,Ozone,8-HR RUN AVG BEGIN HOUR,...,0.040,0.036,0.029,San Luis Rio Colorado Well 10,Calle 15 & Venustiano Carranza Water Well #10,Country Of Mexico,SONORA,NaN,NaN,2018-04-12

### Assigning data
Going the other way, assigning data to a DataFrame is easy. You can assign either a constant value:

In [40]:
data3['Big Data'] = 'cool'
data3['Big Data']

0        cool
1        cool
2        cool
3        cool
4        cool
5        cool
6        cool
7        cool
8        cool
9        cool
10       cool
11       cool
12       cool
13       cool
14       cool
15       cool
16       cool
17       cool
18       cool
19       cool
20       cool
21       cool
22       cool
23       cool
24       cool
25       cool
26       cool
27       cool
28       cool
29       cool
         ...
14787    cool
14788    cool
14789    cool
14790    cool
14791    cool
14792    cool
14793    cool
14794    cool
14795    cool
14796    cool
14797    cool
14798    cool
14799    cool
14800    cool
14801    cool
14802    cool
14803    cool
14804    cool
14805    cool
14806    cool
14807    cool
14808    cool
14809    cool
14810    cool
14811    cool
14812    cool
14813    cool
14814    cool
14815    cool
14816    cool
Name: Big Data, Length: 14817, dtype: object

Or with an iterable of values:

In [41]:
data1['index_backwards'] = range(len(data1), 0, -1)
data1['index_backwards']

0      316
1      315
2      314
3      313
4      312
5      311
6      310
7      309
8      308
9      307
10     306
11     305
12     304
13     303
14     302
15     301
16     300
17     299
18     298
19     297
20     296
21     295
22     294
23     293
24     292
25     291
26     290
27     289
28     288
29     287
      ...
286     30
287     29
288     28
289     27
290     26
291     25
292     24
293     23
294     22
295     21
296     20
297     19
298     18
299     17
300     16
301     15
302     14
303     13
304     12
305     11
306     10
307      9
308      8
309      7
310      6
311      5
312      4
313      3
314      2
315      1
Name: index_backwards, Length: 316, dtype: int64

## There are way more you can do, keep exploring on your own!